adicionado base do sapui5
IsaqueAmorim/MoneyWise-PDI pull request #16
Opened 2023-11-22 16:03 UTC by Furiuss

2023-11-22 16:14 UTC, IsaqueAmorim requested changes

2023-11-22 16:14 UTC, IsaqueAmorim commented on MoneyWise.Web/wwwroot/i18n/i18n.properties
> +miguel=Gay
Por gentileza remover Easter Egg

2023-11-22 16:16 UTC, miguel-sr commented on MoneyWise.Web/wwwroot/i18n/i18n.properties
> +miguel=Gay
Concordo, favor remover.

2023-11-23 16:18 UTC, miguel-sr approved these changes

2023-11-23 20:53 UTC, IsaqueAmorim approved these changes

2023-11-24 21:28 UTC, IsaqueAmorim approved these changes

2023-11-24 21:29 UTC, merged